name: loginapp
description: A simple login app using Flutter and Hive for data storage.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  path_provider: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0  # Added build_runner as a dev dependency
  hive_flutter: ^1.1.0

flutter:
  uses-material-design: true
